services:
  web:
    image: python:3.11-slim
    build: .
    container_name: fastapi
    command: bash -c "
      chmod +x ./wait-for-it.sh &&
      ./wait-for-it.sh db:${MYSQL_PORT} -- uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.39
    restart: always
    container_name: mysqldb
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - 'mysqldb:/var/lib/mysql'
  sql-runner:
    image: mysql:8.0.39
    volumes:
      - .:/app
    container_name: mysqldb_init
    command: >
      bash -c "
      chmod +x /app/wait-for-it.sh
      && /app/wait-for-it.sh web:8000
      && mysql -h ${MYSQL_HOST} -u ${MYSQL_USER} -p${MYSQL_PASSWORD} --default-character-set=utf8mb4 < /app/_db/init.sql"
    depends_on:
      - db
      - web
volumes:
    mysqldb: