services:
  web:
    image: python:3.11-slim
    build: .
    container_name: fastapi
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:8.0.39
    restart: always
    container_name: mysqldb
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    volumes:
      - 'mysqldb:/var/lib/mysql'
volumes:
    mysqldb: