"""empty message

Revision ID: 95bb6fc06448
Revises: 0d43eb57acf1
Create Date: 2024-09-17 03:31:30.542864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95bb6fc06448'
down_revision: Union[str, None] = '0d43eb57acf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_tag', sa.Column('id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('_company_tag_uc', 'company_tag', ['company_id', 'tag_id'])
    op.create_index(op.f('ix_company_tag_id'), 'company_tag', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_tag_id'), table_name='company_tag')
    op.drop_constraint('_company_tag_uc', 'company_tag', type_='unique')
    op.drop_column('company_tag', 'id')
    # ### end Alembic commands ###
